FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=UTC

RUN apt-get update && \
    apt-get install --yes \
    curl openssl zip wget tar ca-certificates build-essential git upx \
    && apt-get clean \
    && rm --recursive --force /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/bin

RUN wget https://go.dev/dl/go1.26.4.linux-amd64.tar.gz && \
    tar -xf go1.26.4.linux-amd64.tar.gz

ENV PATH="${PATH}:/go/bin:/root/go/bin"

WORKDIR /build

COPY . .

CMD ["task","build:internal"]
